const PDFDocument = require('pdfkit');
const fs = require('fs');

function groupItemsByOrder(items) {
  const groups = new Map();
  for (const item of items) {
    const key = item.order_id;
    if (!groups.has(key)) {
      groups.set(key, {
        order_id: item.order_id,
        order_number: item.order_number,
        project_name: item.project_name || '',
        pieces: [],
      });
    }
    groups.get(key).pieces.push(item);
  }
  return [...groups.values()];
}

function createPickupBatchSlip({ batch, customer, items, signerName, signerPhone, signaturePath, outputPath }) {
  const doc = new PDFDocument({ size: 'LETTER', margin: 44 });
  const stream = fs.createWriteStream(outputPath);
  doc.pipe(stream);

  doc.fontSize(20).text('Pickup Batch Slip', { align: 'center' });
  doc.moveDown(0.8);
  doc.fontSize(11);
  doc.text(`Batch: ${batch.batch_number}`);
  doc.text(`Customer: ${customer.company}`);
  doc.text(`Signer: ${signerName}`);
  doc.text(`Phone: ${signerPhone || ''}`);
  doc.text(`Picked up at: ${new Date().toISOString()}`);
  doc.text(`Pieces: ${items.length}`);
  doc.moveDown();

  doc.fontSize(14).text('Pieces by Order');
  doc.moveDown(0.4);
  for (const group of groupItemsByOrder(items)) {
    doc.fontSize(12).text(`Order #${group.order_number} ${group.project_name ? '- ' + group.project_name : ''}`);
    doc.fontSize(9);
    for (const piece of group.pieces) {
      doc.text(`#${piece.piece_no}  ${piece.thickness || ''} ${piece.type || ''}  ${piece.size || ''}  ${piece.weight || ''}`);
    }
    doc.moveDown(0.5);
  }

  doc.moveDown(0.5);
  doc.fontSize(12).text('Signature:');
  if (signaturePath && fs.existsSync(signaturePath)) {
    doc.image(signaturePath, { fit: [220, 90] });
  }
  doc.moveDown(0.4);
  doc.fontSize(8).fillColor('#555').text('Generated by Glass Order. Original signature and batch details are kept for audit.', {
    align: 'center',
  });

  doc.end();
  return new Promise((resolve, reject) => {
    stream.on('finish', resolve);
    stream.on('error', reject);
  });
}

module.exports = {
  createPickupBatchSlip,
  groupItemsByOrder,
};
