#!/usr/bin/env bash
# Build frontend/js/i18n.js by concatenating split sources.
# Source: frontend/js/i18n/{zh.js, en.js, core.js}
# Output: frontend/js/i18n.js
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
DIR="$ROOT/frontend/js/i18n"
OUT="$ROOT/frontend/js/i18n.js"

if [ ! -d "$DIR" ]; then
  echo "ERROR: $DIR not found" >&2
  exit 1
fi
for f in zh.js en.js core.js; do
  if [ ! -f "$DIR/$f" ]; then
    echo "ERROR: missing $DIR/$f" >&2
    exit 1
  fi
done

{
  echo '/* GENERATED by scripts/build-i18n.sh — edit frontend/js/i18n/{zh,en,core}.js instead. */'
  cat "$DIR/zh.js"
  echo ""
  cat "$DIR/en.js"
  echo ""
  cat "$DIR/core.js"
} > "$OUT"

node -c "$OUT"
echo "Built $OUT ($(wc -l < "$OUT") lines)"
